# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='사진으로 대체', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('lnglat', models.CharField(blank=True, help_text='위젯으로 대체', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
