# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 23:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_diary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='diary_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
